//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Version_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public int EmployeeId { get; set; }
        public Nullable<int> SalaryAmount { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
